apiVersion: v2
name: cps1-catalog
description: Helm chart with a collection of Resources, Templates and Packages for the CPS1 Platform
type: application
kubeVersion: ">= 1.30.0-0"
version: 0.4.2
appVersion: "0.4.1"
