{{- if has "apt" .Values.includePackages }}
apiVersion: cps1.tech/v1alpha2
kind: Package
metadata:
  name: apt
spec:
  label: APT Packages
  icon:
    svg: |
      {{- .Files.Get "images/debian.svg" | nindent 6 }}
  properties:
    - name: packages
      label: APT Packages
      tip: |
        You can write only the <package name> to install their latest version,
        but this can lead to distinct results each time the template is built.
        Prefer to use the syntax <package name>=<version> to specify each
        package version.
      kind: tag
      required: true
  setupScript: |
    {{- .Files.Get "scripts/packages/apt.sh" | nindent 4 }}

{{- end }}
