apiVersion: v2
name: cps1-platform
description: Helm chart to install CPS1 Cloud Develpment Environment in your Kubernetes cluster
type: application
kubeVersion: ">= 1.30.0-0"
version: 0.3.1
appVersion: "0.3.1"
