{{- if has "go" .Values.includeTemplates }}
apiVersion: cps1.tech/v1alpha2
kind: Template
metadata:
  name: go-env
spec:
  description: Includes latest Go.
  icon:
    svg: |
      {{- .Files.Get "images/go.svg" | nindent 6 }}
  workspaces:
  - id: go-workspace
    baseImage: ghcr.io/cps-1/base-image:20250624
    packages:
    - inputData:
        version: 1.24.4
      packageRef:
        name: go
        namespace: {{ .Release.Namespace }}
    ports: []
    repositories: []
    env: []
  resources: []
{{- end }}
