{{- if has "python" .Values.includeTemplates }}
apiVersion: cps1.tech/v1alpha2
kind: Template
metadata:
  name: python-env
spec:
  description: Includes latest Python along with other tooling.
  icon:
    svg: |
      {{- .Files.Get "images/python.svg" | nindent 6 }}
  workspaces:
  - id: python-workspace
    baseImage: ghcr.io/cps-1/base-image:20250624
    packages:
    - inputData:
        version: 3.14
      packageRef:
        name: python
        namespace: {{ .Release.Namespace }}
    ports: []
    repositories: []
    env: []
  resources: []
{{- end }}
