
includeTemplates: [ ]

includePackages:
  - apt
  - dotnet
  - go
  - java
  - kubectl
  - nodejs
  - python
  - rust

packages:
  java:
    version:
      values:
        - "25.0.1-tem"
        - "21.0.9-tem"
        - "17.0.17-tem"
      default: "25.0.1-tem"
  dotnet:
    version:
      values:
        - "9.0"
        - "8.0"
      default: "9.0"
  go:
    version:
      values:
        - "1.25.5"
        - "1.24.11"
      default: "1.25.5"
  kubectl:
    version:
      default: "v1.33.3"
  nodejs:
    version:
      values:
        - "v25"
        - "v24"
        - "v22"
        - "v20"
      default: "v25"
  php:
    version:
      values:
        - "8.5"
        - "8.4"
        - "8.3"
        - "8.2"
      default: "8.5"
  python:
    version:
      values:
        - "3.14"
        - "3.13"
        - "3.12"
        - "3.10"
      default: "3.14"

includeResources:
  - mariadb
  - postgres
  - redis
  - mysql

resources:
  mariadb:
    version:
      values:
        - "12.1"
        - "11.8"
        - "11.4"
        - "10.11"
        - "10.6"
      default: "12.1"
  mysql:
    version:
      values:
        - "9.5"
        - "8.4"
        - "8.0"
      default: "9.5"
  postgres:
    version:
      values:
        - "18"
        - "17"
        - "16"
        - "15"
        - "14"
      default: "18"
  opensearch:
    version:
      values:
        - "3"
        - "2"
      default: "3"
  redis:
    version:
      values:
        - "8.4"
        - "8.2"
        - "8.0"
        - "7.4"
      default: "8.4"

# Examples:
#
# awsrdspostgres:
#   allocatedStorage: 10
#   dbInstanceClass: "db.t4g.micro"
#   dbSubnetGroupName: "yourdbsubnet"
#   vpcSecurityGroupIDs:
#     - sg-12345678910111213
#   engineVersion: "17.6"
# awsauroramysql:
#   engineVersion: "8.0.mysql_aurora.3.08.2"
#   dbSubnetGroupName: "yourdbsubnet"
#   vpcSecurityGroupIDs:
#     - sg-12345678910111213
# awsopensearch:
#   vpcOptions:
#     subnetIDs:
#       - subnet-12345678910111213
#     securityGroupIDs:
#       - sg-12345678910111213
#   clusterConfig:
#     instanceType: t3.medium.search
#   ebsOptions:
#     volumeSize: 10
