
includeTemplates: [ ]

includePackages:
  - apt
  - dotnet
  - go
  - java
  - kubectl
  - nodejs
  - python
  - rust

includeResources:
  - mariadb
  - postgres
  - redis
  - mysql

resources: {}
#
# Examples:
#
# awsrdspostgres:
#   allocatedStorage: 10
#   dbInstanceClass: "db.t4g.micro"
#   dbSubnetGroupName: "yourdbsubnet"
#   vpcSecurityGroupIDs:
#     - sg-12345678910111213
#   engineVersion: "17.6"
# awsauroramysql:
#   engineVersion: "8.0.mysql_aurora.3.08.2"
#   dbSubnetGroupName: "yourdbsubnet"
#   vpcSecurityGroupIDs:
#     - sg-12345678910111213
# awsopensearch:
#   vpcOptions:
#     subnetIDs:
#       - subnet-0cf3c7cbf88c1a416
#     securityGroupIDs:
#       - sg-0e4db015e117ed274
#   clusterConfig:
#     instanceType: t3.medium.search
#   ebsOptions:
#     volumeSize: 10
